// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXk9woc0eaj8NVPnCmjsYNQOpK-H903M',
    appId: '1:529124355778:web:c7f7a477e773b00261155b',
    messagingSenderId: '529124355778',
    projectId: 'vias-dit-app',
    authDomain: 'vias-dit-app.firebaseapp.com',
    storageBucket: 'vias-dit-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiRmTbigBhVzDItfQun_EnytXpUUcackk',
    appId: '1:529124355778:android:77de1fdbb898646561155b',
    messagingSenderId: '529124355778',
    projectId: 'vias-dit-app',
    storageBucket: 'vias-dit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLG9hhiGe4XkpNyhUTy4ZmF160Xv_oOpE',
    appId: '1:529124355778:ios:61205e59131d8b0961155b',
    messagingSenderId: '529124355778',
    projectId: 'vias-dit-app',
    storageBucket: 'vias-dit-app.firebasestorage.app',
    iosBundleId: 'com.example.vias',
  );
}
